import Head from "next/head";
import Styles from "../styles/Home.module.scss";
import DashBoard from "./components/Dashboard/Dashboard.component";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={Styles["main"]}>
        <DashBoard />
      </main>
    </>
  );
}
